version: '3.1'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}      
    ports:
      - 3306:3306
    volumes:
      - sword-data:/var/lib/mysql
    networks:
      - sword-network

  sword-node: 
    image: node:19.4
    container_name: sword-node
    command: 'npm run start-server'
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_HOSTNAME: ${MYSQL_HOST}
      SHELL: /bin/bash
    ports:
      - 3000:3000
    volumes:
      - .:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /var/www
    networks:
      - sword-network

volumes:
  sword-data:
    driver: local

networks:
  sword-network:
    name: sword-network
    driver: bridge